#!/bin/bash

# Set this variable to your PDF reader if you use a PDF reader other than Evince, mupdf or okular 
READER=""

# Set this variable to replace the #? prompt with a custom message
PS3="Enter your choice: "

# Usage funtion to display the usage of the script and exit
usage ()
{
	echo "Usage: pselc [options] [directory]"
	echo "Options:"
	echo "   -s    Scan for PDFs in subdirectories as well"
	echo "Warning: -s might be slow if you have hundreds of PDFs in your directory! Use wisely!"
	exit
}

# Process flags
flag=0
DIR=""
case $1 in 
	--help|-h) 
		usage
		;;
	-s) 
		[ -z $2 ] && usage
		flag=1 
		DIR=$2
		;;
	-*)
		echo "Invalid option!"
		usage
		;;
	*)
		DIR=$1 
		;;
esac

# Find a PDF reader. Evince, okular and mupdf are the most common ones around
# Change the READER near the beginning of the script if you don't use any of these
case $READER in
	"")
		[ -n $(which evince) ] && READER=evince
		[ -n $(which mupdf)  ] && READER=mupdf
		[ -n $(which okular) ] && READER=okular
		;;
esac
		
# Exit if no READER found
if [ -z $READER ]
then
	echo "No PDF reader found!"
	echo "If you use any PDF reader other than Evince, okular \
or mupdf then please change the READER variable near the beginning of the script"
	exit
fi

# Exit if directory is not found
find $DIR -maxdepth 1 &>/dev/null
if [ $? -ne 0 ]
then
	echo "No such directory exists!"
	exit
fi

# Read filenames into array
i=0
if [ $flag -eq 1 ]
then
	while read line
	do
	   	array[i]=$line
	    	((i++))
	done < <(find $DIR -type f -name "*.pdf") &>/dev/null
else
	while read line
	do
		array[i]=$line
		((i++))
	done < <(find $DIR -maxdepth 1 -type f -name "*.pdf") &>/dev/null
fi

array_size=${#array[@]}

# Exit if no PDFs found
if [ $array_size -eq 0 ]
then
	echo "No PDFs found in input directory!"
	exit
fi

# Use BASH's inbuilt select utility to prompt for user input
select choice in "${array[@]}"
do
	for (( i=0 ; i<$array_size ; i++ ))
	do
		if [ "$choice" == "${array[i]}"	]
		then
			$READER "$choice" &>/dev/null &
			clear
			exit
		fi
	done
	echo "No such file exists!"
	echo "Choose again!"
done
